import { useMemo, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select'
import { ADVISORY_AUDIENCES } from '@/constants/advisoryAudiences'
import { ACCOUNT_TYPES } from '@/constants/roles'
import { STAFF_NOTIFICATION_EVENT_TYPES } from '@/constants/staffNotificationEventTypes'
import StaffNotificationRecordList from '@/features/notifications/admin/components/StaffNotificationRecordList.jsx'
import { filterStaffNotificationRecords } from '@/features/notifications/admin/staffNotificationFilters.js'
import { formatStaffNotificationEventType } from '@/features/notifications/admin/staffNotificationFormatters.js'

function StaffNotificationsPage({ notificationRecords = null }) {
  const [eventType, setEventType] = useState('ALL')
  const [recipientScope, setRecipientScope] = useState('ALL')
  const filteredRecords = useMemo(
    () => notificationRecords ? filterStaffNotificationRecords(notificationRecords, { eventType, recipientScope }) : [],
    [notificationRecords, eventType, recipientScope],
  )

  function clearFilters() {
    setEventType('ALL')
    setRecipientScope('ALL')
  }

  return <section className="min-w-0" aria-labelledby="staff-notifications-title">
    <h1 className="text-3xl font-bold tracking-tight text-slate-950 md:text-4xl" id="staff-notifications-title">Notification Records</h1>
    <p className="mt-4 max-w-3xl text-lg leading-8 text-slate-600">View notifications automatically generated by trusted backend events. Related references are informational only.</p>
    <div className="mt-6 rounded-lg border border-slate-300 bg-slate-100 p-4 text-sm leading-6 text-slate-800" role="note">Frontend fixtures and filters are not event-generation, authorization, or delivery boundaries. The future backend must generate records from trusted events, determine recipients from authoritative ownership and audience data, handle events idempotently, authorize records for the current staff role, protect member information, retain audit and correlation identifiers internally, and apply appropriate retention and access policies.</div>

    {notificationRecords === null ? <Card className="mt-8 min-w-0"><CardContent className="text-slate-600">Notification records will become available after secure backend integration.</CardContent></Card> : <div className="mt-8 min-w-0 space-y-6">
      <div className="grid min-w-0 gap-4 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] lg:items-end">
        <div className="min-w-0 space-y-2"><Label htmlFor="staff-notification-event-filter">Event type</Label><NativeSelect className="w-full min-w-0" id="staff-notification-event-filter" onChange={(event) => setEventType(event.target.value)} value={eventType}><NativeSelectOption value="ALL">All event types</NativeSelectOption>{Object.values(STAFF_NOTIFICATION_EVENT_TYPES).map((value) => <NativeSelectOption key={value} value={value}>{formatStaffNotificationEventType(value)}</NativeSelectOption>)}</NativeSelect></div>
        <div className="min-w-0 space-y-2"><Label htmlFor="staff-notification-recipient-filter">Recipient scope</Label><NativeSelect className="w-full min-w-0" id="staff-notification-recipient-filter" onChange={(event) => setRecipientScope(event.target.value)} value={recipientScope}>
          <NativeSelectOption value="ALL">All recipients</NativeSelectOption>
          <NativeSelectOption value={ADVISORY_AUDIENCES.ALL_APPROVED_MEMBERS}>All approved members</NativeSelectOption>
          <NativeSelectOption value={ACCOUNT_TYPES.ORGANIZATION}>Organization</NativeSelectOption>
          <NativeSelectOption value={ACCOUNT_TYPES.VOLUNTEER}>Volunteer</NativeSelectOption>
          <NativeSelectOption value={ACCOUNT_TYPES.INDIVIDUAL}>Individual</NativeSelectOption>
        </NativeSelect></div>
        <Button className="w-full lg:w-auto" onClick={clearFilters} type="button" variant="outline">Clear filters</Button>
      </div>
      <StaffNotificationRecordList records={filteredRecords} />
    </div>}
  </section>
}

export default StaffNotificationsPage
