export const STAFF_NOTIFICATION_EVENT_TYPES = Object.freeze({
  INCIDENT_STATUS_CHANGED: 'INCIDENT_STATUS_CHANGED',
  INCIDENT_RESPONSE_CREATED: 'INCIDENT_RESPONSE_CREATED',
  ADVISORY_PUBLISHED: 'ADVISORY_PUBLISHED',
  CRC_MESSAGE_CREATED: 'CRC_MESSAGE_CREATED',
})
